sonar.projectKey=ISCOUTB_DS-finanzaspersonales
sonar.organization=isco-utb
sonar.host.url=https://sonarcloud.io

sonar.projectName=DS-finanzaspersonales
sonar.projectVersion=1.0

# Rutas de código fuente
sonar.sources=lib
sonar.tests=test

# Configuración de cobertura para Dart/Flutter
sonar.dart.coverage.reportPaths=coverage/lcov.info

# Exclusiones comunes para Flutter
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/*.config.dart,**/generated/**

# Configuración adicional
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true

