sonar.projectKey=ISCOUTB_DS-finanzaspersonales
sonar.organization=isco-utb
sonar.host.url=https://sonarcloud.io

sonar.projectName=DS-finanzaspersonales
sonar.projectVersion=1.0
sonar.sources=lib
sonar.dart.coverage.reportPaths=coverage/lcov.info
<<<<<<< HEAD
sonar.sourceEncoding=UTF-8
=======
sonar.sourceEncoding=UTF-8

>>>>>>> 215df600cf9ea3612aed2dae93b48a9409ad248d
