// filepath: c:\Documents\Proyecto_finanzas\DS-finanzaspersonales\sonar-project.properties
sonar.projectKey=ISCOUTB_DS-finanzaspersonales
sonar.organization=isco-utb
sonar.host.url=https://sonarcloud.io

sonar.projectName=DS-finanzaspersonales
sonar.projectVersion=1.0

# Configuración específica para Flutter/Dart
sonar.sources=lib
sonar.tests=test
sonar.sourceEncoding=UTF-8

# CONFIGURACIÓN CRÍTICA PARA FLUTTER COVERAGE
# Usar la propiedad específica de Dart para el reporte LCOV
sonar.dart.lcov.reportPaths=coverage/lcov.info
# Puedes comentar o eliminar la siguiente línea si solo trabajas con Dart,
# o si la específica de Dart ya cubre tus necesidades.
# sonar.coverageReportPaths=coverage/lcov.info

